name: py_env_1
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anyio=4.6.2=py312hca03da5_0
  - appnope=0.1.3=py312hca03da5_1001
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h80987f9_1
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312hca03da5_0
  - attrs=24.3.0=py312hca03da5_0
  - babel=2.11.0=py312hca03da5_0
  - beautifulsoup4=4.12.3=py312hca03da5_0
  - blas=1.0=openblas
  - bleach=6.2.0=py312hca03da5_0
  - bottleneck=1.4.2=py312ha86b861_0
  - brotli-python=1.0.9=py312h313beb8_9
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.2.25=hca03da5_0
  - cairo=1.16.0=h29d4eff_2
  - certifi=2025.6.15=py312hca03da5_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - comm=0.2.1=py312hca03da5_0
  - contourpy=1.3.1=py312h48ca7d4_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.11=py312h313beb8_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - et_xmlfile=1.1.0=py312hca03da5_1
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h313beb8_0
  - fftw=3.3.10=nompi_h3046061_106
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.13.1=h49fc3c0_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonts-conda-forge=1=0
  - fonttools=4.55.3=py312h80987f9_0
  - freetype=2.12.1=h1192e45_0
  - fribidi=1.0.10=h1a28f6b_0
  - gdk-pixbuf=2.42.10=h80987f9_1
  - gettext=0.21.0=h826f4ad_0
  - ghostscript=9.54.0=h6b3803e_2
  - giflib=5.2.2=h80987f9_0
  - glib=2.78.4=h313beb8_0
  - glib-tools=2.78.4=h313beb8_0
  - graphite2=1.3.14=hc377ac9_1
  - graphviz=2.50.0=he1da451_0
  - gts=0.7.6=hde733a8_3
  - h11=0.14.0=py312hca03da5_0
  - harfbuzz=4.3.0=he9eebac_1
  - httpcore=1.0.2=py312hca03da5_0
  - httpx=0.27.0=py312hca03da5_0
  - icu=68.1=hc377ac9_0
  - idna=3.7=py312hca03da5_0
  - imagemagick=7.1.0_8=pl5321hc21dce0_0
  - ipykernel=6.29.5=py312hca03da5_1
  - ipython=8.30.0=py312hca03da5_0
  - jbig=2.1=h1a28f6b_0
  - jedi=0.19.2=py312hca03da5_0
  - jinja2=3.1.4=py312hca03da5_1
  - jpeg=9e=h80987f9_3
  - json5=0.9.25=py312hca03da5_0
  - jsonschema=4.23.0=py312hca03da5_0
  - jsonschema-specifications=2023.7.1=py312hca03da5_0
  - jupyter-lsp=2.2.0=py312hca03da5_0
  - jupyter_client=8.6.0=py312hca03da5_0
  - jupyter_core=5.7.2=py312hca03da5_0
  - jupyter_events=0.10.0=py312hca03da5_0
  - jupyter_server=2.14.1=py312hca03da5_0
  - jupyter_server_terminals=0.4.4=py312hca03da5_1
  - jupyterlab=4.2.5=py312hca03da5_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312hca03da5_0
  - kiwisolver=1.4.8=py312h313beb8_0
  - lcms2=2.12=hba8e193_0
  - lerc=3.0=hc377ac9_0
  - libcxx=14.0.6=h848a8c0_0
  - libdeflate=1.8=h1a28f6b_5
  - libffi=3.4.4=hca03da5_1
  - libgd=2.3.3=h14f8a72_1
  - libgfortran=5.0.0=11_3_0_hca03da5_28
  - libgfortran5=11.3.0=h009349e_28
  - libglib=2.78.4=h0a96307_0
  - libiconv=1.16=h80987f9_3
  - libopenblas=0.3.21=h269037a_0
  - libpng=1.6.39=h80987f9_0
  - librsvg=2.54.4=h6a74ff0_0
  - libsodium=1.0.18=h1a28f6b_0
  - libtiff=4.4.0=h2fd578a_2
  - libtool=2.4.7=h313beb8_0
  - libwebp=1.3.2=ha3663a8_0
  - libwebp-base=1.3.2=h80987f9_1
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.9.14=h8c5e841_0
  - llvm-openmp=14.0.6=hc6e5704_0
  - lz4-c=1.9.4=h313beb8_1
  - markupsafe=2.1.3=py312h80987f9_1
  - matplotlib=3.10.0=py312hca03da5_0
  - matplotlib-base=3.10.0=py312h7ef442a_0
  - matplotlib-inline=0.1.6=py312hca03da5_0
  - mistune=2.0.4=py312hca03da5_0
  - nbclient=0.8.0=py312hca03da5_0
  - nbconvert=7.16.4=py312hca03da5_0
  - nbformat=5.10.4=py312hca03da5_0
  - ncurses=6.4=h313beb8_0
  - nest-asyncio=1.6.0=py312hca03da5_0
  - notebook-shim=0.2.3=py312hca03da5_0
  - numexpr=2.10.1=py312h5d9532f_0
  - numpy=2.0.1=py312h7f4fdc5_1
  - numpy-base=2.0.1=py312he047099_1
  - openjpeg=2.4.0=h0ed58ac_2
  - openpyxl=3.1.5=py312h80987f9_0
  - openssl=3.0.16=h02f6b3c_0
  - overrides=7.4.0=py312hca03da5_0
  - packaging=24.2=py312hca03da5_0
  - pandas=2.2.3=py312hcf29cfe_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - pango=1.50.7=h7271ec9_0
  - parso=0.8.4=py312hca03da5_0
  - pcre2=10.42=hb066dcc_1
  - pdfminer.six=20221105=pyhd8ed1ab_0
  - pdfplumber=0.9.0=pyhd8ed1ab_0
  - perl=5.32.1=0_h1a28f6b_perl5
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.0.0=py312hfaf4e14_0
  - pip=24.2=py312hca03da5_0
  - pixman=0.40.0=h1a28f6b_0
  - pkg-config=0.29.2=h1a28f6b_0
  - platformdirs=3.10.0=py312hca03da5_0
  - prometheus_client=0.21.0=py312hca03da5_0
  - prompt-toolkit=3.0.43=py312hca03da5_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - psutil=5.9.0=py312h80987f9_1
  - pthread-stubs=0.3=h1a28f6b_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.15.1=py312hca03da5_1
  - pyparsing=3.2.0=py312hca03da5_0
  - pysocks=1.7.1=py312hca03da5_0
  - python=3.12.8=h99e199e_0
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-fastjsonschema=2.20.0=py312hca03da5_0
  - python-json-logger=3.2.1=py312hca03da5_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - pytz=2024.1=py312hca03da5_0
  - pyyaml=6.0.2=py312h80987f9_0
  - pyzmq=26.2.0=py312h313beb8_0
  - rapidfuzz=3.12.1=py312h313beb8_0
  - readline=8.2=h1a28f6b_0
  - referencing=0.30.2=py312hca03da5_0
  - requests=2.32.3=py312hca03da5_1
  - rfc3339-validator=0.1.4=py312hca03da5_0
  - rfc3986-validator=0.1.1=py312hca03da5_0
  - rpds-py=0.22.3=py312h2aea54e_0
  - send2trash=1.8.2=py312hca03da5_1
  - setuptools=75.1.0=py312hca03da5_0
  - six=1.16.0=pyhd3eb1b0_1
  - sniffio=1.3.0=py312hca03da5_0
  - soupsieve=2.5=py312hca03da5_0
  - sqlite=3.45.3=h80987f9_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - terminado=0.17.1=py312hca03da5_0
  - tinycss2=1.2.1=py312hca03da5_0
  - tk=8.6.14=h6ba3021_0
  - tornado=6.4.2=py312h80987f9_0
  - traitlets=5.14.3=py312hca03da5_0
  - typing-extensions=4.12.2=py312hca03da5_0
  - typing_extensions=4.12.2=py312hca03da5_0
  - tzdata=2024b=h04d1e81_0
  - unicodedata2=15.1.0=py312h80987f9_1
  - urllib3=2.2.3=py312hca03da5_0
  - wand=0.6.10=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py312hca03da5_2
  - websocket-client=1.8.0=py312hca03da5_0
  - wheel=0.44.0=py312hca03da5_0
  - xorg-libice=1.1.2=h5505292_0
  - xorg-libsm=1.2.5=h5505292_0
  - xorg-libx11=1.8.11=h6a5fb8c_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xorg-libxext=1.3.6=hd74edd7_0
  - xorg-libxrender=0.9.12=h5505292_0
  - xorg-libxt=1.3.1=h5505292_0
  - xz=5.4.6=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zeromq=4.3.5=h313beb8_0
  - zlib=1.2.13=h18a0788_1
  - zstd=1.5.6=hfb09047_0
  - pip:
      - altair==5.5.0
      - annotated-types==0.7.0
      - arrow==1.4.0
      - asgiref==3.11.0
      - binaryornot==0.4.4
      - blinker==1.9.0
      - cachetools==6.1.0
      - cffi==2.0.0
      - chardet==5.2.0
      - click==8.1.8
      - configparser==7.2.0
      - cookiecutter==2.6.0
      - cron-converter==1.2.2
      - cryptography==46.0.3
      - deprecation==2.1.0
      - django==5.2.8
      - django-stubs==5.2.7
      - django-stubs-ext==5.2.7
      - django-timezone-utils==0.15.0
      - env-tools==2.4.0
      - factory-boy==3.3.3
      - faker==38.2.0
      - frozendict==2.4.7
      - gitdb==4.0.12
      - gitpython==3.1.44
      - greenlet==3.2.4
      - grpcio==1.76.0
      - kaleido==0.2.1
      - langdetect==1.0.9
      - libretranslatepy==2.1.1
      - lxml==5.3.1
      - markdown-it-py==4.0.0
      - matplotlib-venn==1.1.2
      - mdurl==0.1.2
      - mypy==1.18.2
      - mypy-extensions==1.1.0
      - narwhals==1.31.0
      - pathspec==0.12.1
      - playwright==1.54.0
      - plotly==6.0.1
      - protobuf==4.25.8
      - psycopg==3.2.12
      - psycopg-binary==3.2.12
      - psycopg-pool==3.2.7
      - pyarrow==21.0.0
      - pydantic==2.11.10
      - pydantic-core==2.33.2
      - pydeck==0.9.1
      - pyee==13.0.0
      - pyjwt==2.10.1
      - pymupdf==1.25.2
      - pypdf2==3.0.1
      - python-dotenv==1.2.1
      - python-slugify==8.0.4
      - redis==5.3.1
      - reportlab==4.4.5
      - restrictedpython==8.1
      - rich==14.2.0
      - scipy==1.15.2
      - seaborn==0.13.2
      - sentry-sdk==2.45.0
      - shellingham==1.5.4
      - smmap==5.0.2
      - sqlparse==0.5.3
      - statsd==4.0.1
      - streamlit==1.47.0
      - tabulate==0.9.0
      - tenacity==9.1.2
      - text-unidecode==1.3
      - thefuzz==0.22.1
      - tini==4.0.0
      - toml==0.10.2
      - tqdm==4.67.1
      - translate==3.6.1
      - typer==0.20.0
      - types-pyyaml==6.0.12.20250915
      - typing-inspection==0.4.2
      - watchdog==6.0.0
prefix: /Users/adeboye.adejoro/anaconda3/envs/py_env_1
